@echo off
REM ============================================================================
REM setup_autostart.bat - Windows Task Scheduler Auto-Start Configuration
REM ============================================================================
REM This script configures Windows Task Scheduler to start PM2 and all AI
REM Employee processes automatically on system boot.
REM
REM IMPORTANT: Run this script as Administrator!
REM ============================================================================

setlocal EnableDelayedExpansion

echo.
echo ============================================================================
echo   Platinum Tier AI Employee - Auto-Start Configuration
echo ============================================================================
echo.

REM Check for administrator privileges
net session >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] This script must be run as Administrator!
    echo.
    echo Please right-click on this script and select "Run as administrator".
    echo.
    pause
    exit /b 1
)

echo [OK] Running with administrator privileges.
echo.

REM Get the directory where this script is located
set "SCRIPT_DIR=%~dp0"

REM Remove trailing backslash
set "VAULT_DIR=%SCRIPT_DIR:~0,-1%"

echo [INFO] Vault directory: %VAULT_DIR%
echo.

REM ============================================================================
REM Step 1: Check if PM2 is installed globally
REM ============================================================================
echo [1/4] Checking PM2 installation...
where pm2 >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo [ERROR] PM2 is not installed or not in PATH.
    echo Please install Node.js and PM2 first:
    echo   1. Install Node.js from https://nodejs.org
    echo   2. Run: npm install -g pm2
    pause
    exit /b 1
)

for /f "tokens=*" %%v in ('pm2 --version') do echo [OK] PM2 version: %%v
echo.

REM ============================================================================
REM Step 2: Delete existing task if present
REM ============================================================================
echo [2/4] Removing existing auto-start task (if any)...
schtasks /Delete /TN "PlatinumTierAIEmployee" /F >nul 2>nul
echo [OK] Previous task removed (if existed).
echo.

REM ============================================================================
REM Step 3: Create the scheduled task
REM ============================================================================
echo [3/4] Creating Windows Task Scheduler task...
echo.

REM Create a batch file that will be run at startup
set "STARTUP_BAT=%VAULT_DIR%\scripts\pm2_startup.bat"

echo Creating startup script: %STARTUP_BAT%
(
    echo @echo off
    echo REM Auto-generated by setup_autostart.bat
    echo REM Runs at system startup to start PM2 processes
    echo.
    echo cd /d "%VAULT_DIR%"
    echo.
    echo REM Wait for network to be available
    echo timeout /t 30 /nobreak ^>nul
    echo.
    echo REM Start PM2 processes
    echo pm2 start ecosystem.config.js
    echo.
    echo REM Save PM2 process list
    echo pm2 save
    echo.
    echo exit /b 0
) > "%STARTUP_BAT%"

echo [OK] Startup script created.
echo.

REM Create the scheduled task
echo Creating scheduled task "PlatinumTierAIEmployee"...
schtasks /Create /TN "PlatinumTierAIEmployee" ^
    /TR "\"%STARTUP_BAT%\"" ^
    /SC ONSTART ^
    /RU SYSTEM ^
    /RL HIGHEST ^
    /F

if %ERRORLEVEL% neq 0 (
    echo [ERROR] Failed to create scheduled task.
    pause
    exit /b 1
)

echo [OK] Scheduled task created successfully.
echo.

REM ============================================================================
REM Step 4: Verify the task
REM ============================================================================
echo [4/4] Verifying scheduled task...
echo.
schtasks /Query /TN "PlatinumTierAIEmployee"
echo.

echo ============================================================================
echo   Configuration Complete!
echo ============================================================================
echo.
echo The AI Employee will now start automatically on system boot.
echo.
echo Task Details:
echo   Name: PlatinumTierAIEmployee
echo   Trigger: System Startup
echo   Run As: SYSTEM (Highest privileges)
echo   Script: %STARTUP_BAT%
echo.
echo To manually start the processes now, run:
echo   start.bat
echo.
echo To view or modify the task:
echo   1. Open Task Scheduler (taskschd.msc)
echo   2. Find "PlatinumTierAIEmployee" in the task list
echo.
echo To remove auto-start:
echo   schtasks /Delete /TN "PlatinumTierAIEmployee" /F
echo.
echo ============================================================================
echo.

pause
exit /b 0
